### ISSUE TITLE
using the code for aperiodic monotiles?

### ISSUE THREAD

**Issue by davehorner** [BorysMinaiev/jigsaw-puzzle-solver#1]
I haven't yet spent any time with your code yet.  The articles you wrote were great.  I'm interested in aperiodic monotile tilings.

There are svg and other formats available of the monotiles.
https://github.com/christianp/aperiodic-monotile

Could you envision your code being able(with modification) to tile such pieces?

**Comment by bminaiev** [comment]
The code quite heavily uses the fact that the pieces look like normal jigsaw pieces (e.g., have 4 corners), so I think many changes need to be done to support different formats. 

However, you can probably reuse some parts of the code if you are going to write your solver for aperiodic monotile tilings.

**Comment by KorigamiK** [comment]
> I haven't yet spent any time with your code yet. The articles you wrote were great. I'm interested in aperiodic monotile tilings.
> 
> There are svg and other formats available of the monotiles. https://github.com/christianp/aperiodic-monotile
> 
> Could you envision your code being able(with modification) to tile such pieces?

These look soo painful to solve by hand :sob:

**Comment by davehorner** [comment]
don't mean to leave this open.  Thank you for the responses.
